### ISSUE TITLE
Getting "No Network Detected" during installation on known working gear

### ISSUE THREAD

**Issue by CullenJWebb** [gamer-os/install-media#21]
I'm installing on a laptop motherboard that can boot and connect to the internet with other operating systems.

I choose "install GamerOS" at boot and after running for a while it says there is no detected network. I can see that it's being assigned an IP address by DHCP, and I've also assigned one manually while debugging, but I can't get it to detect the network. I've attempted changing my DNS to 1.1.1.1 and 1.0.0.1 without any luck there, same thing. I've checked the networking settings in the bios and nothing changes.

When I click "retry" I can see that it downloads ~4kb and sends ~1kb per attempt to github:
![gameros_data_transfer](https://user-images.githubusercontent.com/2952787/87840964-4358b200-c870-11ea-95f4-24640a7f991b.png)

Any advice?

Thanks so much for your time!

**Comment by CullenJWebb** [comment]
It's working in the standard Arch Linux installer:
![IMG_20200721_094952](https://user-images.githubusercontent.com/2952787/88068301-06294400-cb3e-11ea-89ae-2ff35e5681d6.jpg)

And today when attempting in GamerOS I'm getting SSL errors when trying curl: 
![IMG_20200721_095220](https://user-images.githubusercontent.com/2952787/88068396-20632200-cb3e-11ea-9324-3c18734b7ae2.jpg)

**Comment by sharkwouter** [comment]
It's probably related to the system time. Could you try running the ``date`` command from the GamerOS live cd? You can just select no after you selected the disk to get access to the command line.

**Comment by CullenJWebb** [comment]
Progress! The date set in my UEFI was incorrect and that was likely the cause of the network errors. However, I'm getting a new error after selecting my SSD:
![IMG_20200721_145052](https://user-images.githubusercontent.com/2952787/88094686-fae80f80-cb61-11ea-8f27-288fc67433cb.jpg)

"Partition(s) on /dev/sda are being used."

This is on a blank SSD with no prior partitions. I'm running the install media from a USB drive and I'm selecting the SSD during installation.

**Comment by CullenJWebb** [comment]
I'm no longer getting the SSD issue, I've installed and am up and running now, woot!
