### ISSUE TITLE
freeze during boot process

### ISSUE THREAD

**Issue by tommy4st** [gamer-os/install-media#8]
The image freezed when the boot process reaches "Triggering uevents". Using the kernel parameter "debug" I figured out it crashes when nouveaufb tries to change the display resolution (sorry no screenshot here yet). Sadly the same problem occurs with the Manjaro Live-Image as well. The [system](https://www.zotac.com/us/product/mini_pcs/magnus-en1070k) is setup as pure UEFI.

My quickfix was to press `e` in the boot menu and add the kernel parameter "nomodeset". Then the boot process completes and I can install GamerOS as intended. Maybe this parameter can be added as default, because the install process is pure text console and should be fine?

![gameros-freeze](https://user-images.githubusercontent.com/2656837/71887972-7abb0900-313f-11ea-8fe0-76781236c72e.png)

Maybe it's a wontfix, but I think it's still worth mentioning here or the FAQ.

**Comment by alkazar** [comment]
@tommy4st I think this should be fixed with the new ISO build: https://github.com/gamer-os/install-media/releases/download/2020-03-12/gameros-2020.03.12-x86_64.iso

If you have a chance to test it out, please report back. Thanks!

**Comment by vicentesuarez** [comment]
This is happening for me as well. The solution by @tommy4st worked.

Just downloaded from https://github.com/ChimeraOS/install-media/releases/download/2021-07-01/chimeraos-2021.07.01-x86_64.iso

**Comment by alkazar** [comment]
@vicentesuarez Thanks for reporting. Looks like this was missed when upgrading to the new Arch installer.

Thanks for reporting. It should be fixed in the next release.

Note: fixed in 35b6e83
